### PR TITLE
A Perl script for making the pipelines

### PR DESCRIPTION
**Pull request by CAUSA**
A Perl script for making the pipelines for mapping raw reads to the reference genome, useful when there are a lot of raw reads (.fastq files) to be mapped.
#Save all your .fastq files in the DATA_DIR in a sub dir, named as SampleID
#Name you files like: 
#SampleID-001-R1.fastq
#SampleID-001-R2.fastq
#SampleID-002-R1.fastq
#SampleID-002-R2.fastq
#......
#SampleID-100-R1.fastq
#SampleID-100-R2.fastq

### CODE REVIEW

**Comment by rtraborn** [comment]
Hi @CAUSA: thanks for adding this! 
Before I merge your pull request, could you please add a `0README` file on how to reproduce your example?
-Taylor

**Comment by rtraborn** [comment]
@CAUSA: this looks great. Thanks for making these changes.
One quick thing to do before I merge: please correct the name of the file `Reame.txt` to `0README`  as follows:
```
git mv Reame.txt 0README
git add 0README
git commit -m "Updated name of README"
git push origin master
```

This is really coming together- thanks again!
-Taylor

**Comment by CAUSA** [comment]
@rtraborn 
Done!
Thanks!
Let work together to make it easy!

-Xiaolong

**Comment by rtraborn** [comment]
Splendid- thanks!
-Taylor

**Pull request merged**
